#!/bin/sh
# author  : Joshua Gomez
# version : 1.0
# brief   : shell script to build android projects and fetch apk to current directory

# store current path to a variable
current_path="$PWD"

# function to print values in yellow color
print_in_bold_yellow()
{
	echo
	bold=$(tput bold)
	YELLOW='\033[1;33m'
	echo "${YELLOW}${bold}[BUILD-AND-FETCH] >>> $1"
}

# function to print values in yellow color
print_in_bold_green()
{
	echo
	bold=$(tput bold)
	GREEN='\033[0;32m'
	echo "${GREEN}${bold}[BUILD-AND-FETCH] >>> $1"
}

# function to build apps and fetch apk to current path
build_and_fetch()
{
	# store project path to variable
	path=$1
	# validate path
	if [ $path = "" ]
	then
		echo "Invalid path : $path"
	else 
		# goto path
		cd $path
		print_in_bold_yellow "Building $path"
		# build project
		./gradlew app:assembleDebug
		# goto apk path
		cd "$path/app/build/outputs/apk/debug/"
		# copy apk to current path
		source="*.apk" 
		info=$(cp -v $source $current_path)
		print_in_bold_yellow "Fetch $info"
		# go back to current path
		cd $current_path
	fi
}

build_and_fetch ~/meaa/repo/vendor/quest/Phone/PhoneHMI
build_and_fetch ~/meaa/repo/vendor/quest/Phone/PhoneService
build_and_fetch ~/meaa/repo/vendor/quest/Phone/DeviceManagerService


print_in_bold_green 'SUCCESSFULLY COMPLETED'
echo
